#! /bin/sh
### BEGIN INIT INFO
# Provides:          ihm-robot
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Run /etc/ihm-robot if it exist
### END INIT INFO

# Apres cette ligne les commandes executees en fonction du parametre passe en ligne de commande

case "$1" in

    start)

        # Commandes executees avec le parametre start (celui lors du boot)
        /home/pi/IHM_robot.py

        ;;

    stop)

        # Commandes executees avec le parametre stop (celui lors de l'arret du systeme)

        ;;

    reload|restart)

        $0 stop

        $0 start

        ;;

    *)

        echo "Usage: $0 start|stop|restart|reload"

        exit 1

esac

exit 0
